# Generated by Django 2.1.7 on 2019-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhowtorepo',
            name='howto_description',
            field=models.CharField(max_length=50),
        ),
    ]
