AWS_UPLOAD_BUCKET = "msu-hotlibrary-uploads"

AWS_UPLOAD_USERNAME = "hotlibrary-user"

AWS_UPLOAD_GROUP = "hotlib"

AWS_UPLOAD_REGION = 'us-east-1'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIA2BFFEPA44EWLYRRT"

AWS_UPLOAD_SECRET_KEY = "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"

